trigger:
- '*'

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    configuration: 'Release'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.DefaultWorkingDirectory)/Projectx/bin/obj/Release'
    artifact: 'projectX'
    publishLocation: 'pipeline'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyWebApp'
    appType: 'webApp'
    WebAppName: 'walter-webap'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

