trigger:
- '*'

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    configuration: 'Release'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'D:\a\1\s\Projectx\'
    artifact: 'projectX'
    publishLocation: 'pipeline'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'projectX'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyWebApp'
    appType: 'webApp'
    WebAppName: 'walter-webap'
    packageForLinux: 'D:\a\1\s\Projectx\obj\Release\'


