trigger:
- '*'

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    configuration: 'Release'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'projectx'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'projectx'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyWebApp'
    appType: 'webApp'
    WebAppName: 'walter-webap'
    packageForLinux: '$(System.ArtifactsDirectory)\**\*.zip'


