trigger:
- '*'

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: '

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    configuration: 'Release'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64''



